development:
  adapter: postgresql
  encoding: utf8
  database: houston_development
  host: localhost

test: &test
  adapter: postgresql
  encoding: utf8
  database: houston_test
  host: localhost

cucumber:
<<: *test
